# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "0 0 * * WED"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run crawl
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          author_name: "Newso"
          author_email: "official@antller.com"
          committer_name: "Newso"
          committer_email: "official@antller.com"
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: github action crawling article commit ${{ github.event.repository.updated_at}}
          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          # new_branch: 'gh-pages'
